# Generated by Django 4.2.1 on 2023-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='member1',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
