# Generated by Django 4.2.1 on 2023-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member1',
            name='date',
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
