# Generated by Django 4.2.1 on 2023-05-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lastname',
        ),
    ]
